# Generated by Django 4.2.14 on 2025-11-06 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('prep_time_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_time_min', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('serves', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('spice_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('prep_complexity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
