# Generated by Django 4.2.14 on 2025-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the recipe page (optional)', null=True),
        ),
    ]
